USE SULTANOV_10PZMAN
CREATE TABLE Ученики(
ID INT PRIMARY KEY IDENTITY(1,1),
Фамилия VARCHAR(60) NOT NULL,
Предмет VARCHAR(60) NOT NULL,
Школа VARCHAR(60) NOT NULL,
Баллы FLOAT CHECK((Баллы>=0) AND (Баллы <= 100))NULL)